version: 2.1
commands:
  destroy-environment:
    description: Destroy Kubernetes Stack on Fail
    parameters:
      envname:
        default: "udacity-capstone-project"
        type: string
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
             aws cloudformation delete-stack --stack-name << parameters.envname >>-management
             aws cloudformation delete-stack --stack-name << parameters.envname >>-nodegroup
             aws cloudformation delete-stack --stack-name << parameters.envname >>-cluster
             aws cloudformation delete-stack --stack-name << parameters.envname >>-infrastructure

jobs:
  install-build-lint:
    docker:
      - image: python:3.9-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      # run lint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  build-image-push:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and Tag Docker Image
          command: |
            docker build --tag=$DOCKER_IMAGE_NAME .
            docker image ls
      - run:
          name: Upload Docker to Dockerhub
          command: |
            echo "Docker ID and Image: $DOCKER_IMAGE_NAME"
            docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
            docker tag $DOCKER_IMAGE_NAME $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:${CIRCLE_WORKFLOW_ID}
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:${CIRCLE_WORKFLOW_ID}
  setup-kubernetes:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      - run:
          name: Create Kubernetes Infrastructure
          command: |
            cd .circleci/cloudformation
            aws cloudformation deploy \
              --template-file infrastructure.yml \
              --tags project=${ENVIRONMENT_NAME} \
              --stack-name "${ENVIRONMENT_NAME}-infrastructure" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://infrastructure-parameters.json
      - run:
          name: Create Kubernetes Cluster
          command: |
            cd .circleci/cloudformation
            aws cloudformation deploy \
              --template-file clusters.yml \
              --tags project=${ENVIRONMENT_NAME} \
              --stack-name "${ENVIRONMENT_NAME}-cluster" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://clusters-parameters.json \
              --capabilities CAPABILITY_NAMED_IAM
          no_output_timeout: 15m
      - run:
          name: Create NodeGroup
          command: |
            cd .circleci/cloudformation
            aws cloudformation deploy \
              --template-file nodegroups.yml \
              --tags project=${ENVIRONMENT_NAME} \
              --stack-name "${ENVIRONMENT_NAME}-nodegroup" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://nodegroups-parameters.json \
              --capabilities CAPABILITY_NAMED_IAM

      - run:
          name: Create Management Node
          command: |
            cd .circleci/cloudformation
            aws cloudformation deploy \
              --template-file managementnode.yml \
              --tags project=${ENVIRONMENT_NAME} \
              --stack-name "${ENVIRONMENT_NAME}-management" \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides file://managementnode-parameters.json \
              --output text >> ~/Deployed.txt
            cat ~/Deployed.txt
      - run:
          name: Retrieve Management Node IP Address for Ansible Playbook Inventory File
          command: |
            echo [management] > ~/inventory.txt
            MANAGEMENT_PUBLIC_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=${ENVIRONMENT_NAME}-ManagementNode" \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text)
            echo $MANAGEMENT_PUBLIC_IP >> ~/inventory.txt
            cat ~/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt
            - Deployed.txt
      - destroy-environment:
          envname: ${ENVIRONMENT_NAME}
  configure-kubernetes-stack:
    docker:
      - image: cimg/python:3.11.1-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "02:88:fd:60:96:f8:32:13:65:95:87:75:f8:d2:cb:75"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies to Circle Ci Image
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            pip install ansible
            sudo apt install -y tar gzip curl
      - run:
          name: Configure Management Instance
          command: |
            if grep -q "No changes to deploy" ~/Deployed.txt
              then
                cat ~/inventory.txt
                echo "Management Node Up, Running and Configured"
              else
                cat ~/inventory.txt
                cd .circleci/ansible
                ansible-playbook -i ~/inventory.txt server-config.yml
              fi
      - run:
          name: Configure EKS Cluster
          command: |
            if grep -q "No changes to deploy" ~/Deployed.txt
              then
                cat ~/inventory.txt
                echo "Management Node Up, Running and Configured."
              else
                cat ~/inventory.txt
                cd .circleci/ansible
                ansible-playbook -i ~/inventory.txt cluster-config.yml
              fi
      - run:
          name: ELB Wait for Availability
          command: |
            if grep -q "No changes to deploy" ~/Deployed.txt
              then
                cat ~/inventory.txt
                echo "Management Node Up, Running and Configured."
              else
                cat ~/inventory.txt
                echo "Hibernate and Wait"
                sleep 60
              fi
      - run:
          name: ELB Domain Name
          command: |
            cat ~/inventory.txt
            cd .circleci/ansible
            ansible-playbook -i ~/inventory.txt save-dns.yml
            aws elbv2 describe-load-balancers \
            --query 'LoadBalancers[*].[LoadBalancerName,DNSName,LoadBalancerArn]' \
            --output text >> ~/dns.txt
            cat ~/dns.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - dns.txt
      #- destroy-environment:
          #envname: ${ENVIRONMENT_NAME}
  deploy-docker-image:
    docker:
      - image:  cimg/python:3.11.1-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "02:88:fd:60:96:f8:32:13:65:95:87:75:f8:d2:cb:75"
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies to Circle Ci Image
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            pip install ansible
            sudo apt install -y tar gzip curl
      - run:
          name: Deploy Docker Image
          command: |
            cat ~/inventory.txt
            cd .circleci/ansible
            ansible-playbook -i ~/inventory.txt deploy-app.yml
          no_output_timeout: 2m
workflows:
  default:
    jobs:
      - install-build-lint
      - build-image-push:
          requires:
           - install-build-lint
      - setup-kubernetes
      - configure-kubernetes-stack:
           requires: [setup-kubernetes,build-image-push]
      - deploy-docker-image:
           requires:
             - configure-kubernetes-stack

