apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-project-service
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
