apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project-deployment
  labels:
    app: udacity-capstone-project-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: udacity-capstone-project-app
  template:
    metadata:
      labels:
        app: udacity-capstone-project-app
    spec:
      containers:
        - name: udacity-capstone-project-app
          image: ibrahimballa20/udacity-capstone-project
          ports:
            - containerPort: 80
